CREATE TABLE IF NOT EXISTS SUDOKUS (
                                      ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    C1 VARCHAR(9) NOT NULL,
    C2 VARCHAR(9) NOT NULL,
    C3 VARCHAR(9) NOT NULL,
    C4 VARCHAR(9) NOT NULL,
    C5 VARCHAR(9) NOT NULL,
    C6 VARCHAR(9) NOT NULL,
    C7 VARCHAR(9) NOT NULL,
    C8 VARCHAR(9) NOT NULL,
    C9 VARCHAR(9) NOT NULL
);